/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description Two distinct modes behind one endpoint, chosen by whether `search` is
         *     given:
         *
         *     - **search mode** (`search` present): powers a type-to-search-and-
         *       select UI control (an autocomplete/typeahead), not a browsable list
         *       -- a caller there wants "the handful of courses matching what's
         *       typed so far", not a page out of the full table. Returns a bare
         *       `list[CourseResponse]`, capped at 10 matches, with no
         *       PaginatedResponse envelope: `total`/`limit`/`offset` describe a
         *       paginated browse, which this isn't, so they'd only be noise here.
         *       `limit`/`offset` are ignored in this mode.
         *     - **browse mode** (no `search`): the standard paginated list, wrapped
         *       in `PaginatedResponse`. Sorted by difficulty_rank ascending with
         *       NULLs last: the 17 courses with a ShotLink data gap have no
         *       difficulty_rank at all (see docker/init/schema.sql and
         *       src/transform.py's build_course_difficulty(), which computes this
         *       same column with `F.asc_nulls_last` for the identical reason --
         *       Postgres's plain `ASC` would otherwise sort NULLs *first*, putting
         *       "no rank" courses ahead of "hardest" instead of after "easiest").
         *
         *     `limit` is capped at 100 via FastAPI's `Query(le=100)`, which rejects
         *     an out-of-range value with a 422 rather than silently clamping it --
         *     a client asking for 200 rows and quietly getting 100 back with no
         *     indication would be a harder bug to notice than a validation error.
         */
        get: operations["list_courses_api_v1_courses__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_api_v1_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Same browse/search split as GET /api/v1/courses (see that endpoint's
         *     docstring for the full reasoning) -- search mode returns a bare,
         *     10-match-capped `list[PlayerSummary]` for a typeahead; browse mode
         *     returns the full player list as a `PaginatedResponse`, sorted by name
         *     ascending.
         *
         *     Both modes query `DISTINCT player_id, player`: `player_season_stats`
         *     has one row per (player_id, season), so a plain SELECT would return
         *     Rory McIlroy once per season he has data for rather than once.
         *
         *     `limit` is capped at 100 via `Query(le=100)`, rejecting an out-of-range
         *     value with a 422 rather than silently clamping it -- same reasoning as
         *     courses.py's list endpoint.
         */
        get: operations["list_players_api_v1_players__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Career Summary
         * @description Career totals computed across all of `player_id`'s seasons -- not a
         *     stored row, so this is one aggregate query rather than a lookup.
         *
         *     careerAverageStrokesGained is a WEIGHTED average --
         *     SUM(sum_sg_total) / SUM(tournaments_played) across the player's
         *     career -- not the mean of each season's avg_sg_total. An unweighted
         *     mean-of-means would reintroduce the exact small-sample distortion
         *     src/transform.py's difficulty ranking already had to correct for once
         *     (see its build_course_difficulty() docstring): a 3-tournament season
         *     would count exactly as much as a 25-tournament one, when the whole
         *     point of "career average" is that heavier seasons should count more.
         *
         *     The SUM(tournaments_played) denominator is filtered to
         *     `sum_sg_total IS NOT NULL` seasons specifically -- not every season
         *     the player has a row for. Postgres's SUM() already silently skips NULL
         *     sum_sg_total values in the numerator (a season in the ShotLink data
         *     gap, see api/models/player.py), so leaving the denominator unfiltered
         *     would divide a partial numerator by a full denominator: e.g. Rory
         *     McIlroy's 2022 (tournaments_played=10, sum_sg_total NULL) would count
         *     those 10 tournaments against the average while contributing zero
         *     strokes-gained to it, silently dragging the number down. Filtering
         *     the denominator to the same qualifying seasons as the numerator keeps
         *     the two consistent; NULLIF guards the remaining edge case of a player
         *     whose every season falls in the gap (denominator, and hence the
         *     result, is NULL rather than a division error -- see
         *     PlayerCareerSummary's Optional typing for this field).
         *
         *     careerStrokesGained (SUM(sum_sg_total), unfiltered) has no such
         *     ambiguity -- it's already a sum, not a rate, so there's nothing to
         *     weight.
         */
        get: operations["get_player_career_summary_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Seasons
         * @description Every `player_season_stats` row for `player_id`, sorted season
         *     ascending. No PaginatedResponse envelope: a player has at most a
         *     handful of seasons in the current dataset (~6), so this isn't a
         *     "browse many things" endpoint the way GET /api/v1/players is.
         */
        get: operations["get_player_seasons_api_v1_players__player_id__seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboards/season/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Season Leaderboard
         * @description Ranks `year`'s players by `category`, using that category's stored
         *     per-season rank column (ascending -- rank 1 first). Rows are excluded
         *     if EITHER that rank column OR the underlying value column is null:
         *     the rank column alone isn't a reliable enough filter, because the
         *     `sum_sg_*` columns' stored rank is (as of this writing) populated even
         *     for the 203 rows with a ShotLink data gap in the value itself -- e.g.
         *     a real player-season with sum_sg_total NULL but sum_sg_total_rank=302.
         *     A handful of avg_sg_* rows exhibit the same mismatch. Filtering on
         *     both columns keeps every returned entry's `value` field genuinely
         *     displayable, regardless of which family's null-handling quirk applies.
         *     The 10-tournament qualifying threshold behind avg_sg_*_rank's own
         *     nulls is threshold logic already baked into the stored column by
         *     src/transform.py -- this endpoint doesn't reimplement it, just
         *     respects whatever's already null.
         *
         *     A `year` with no rows at all (outside the dataset's 2017-2022 range,
         *     or simply a typo) returns `{"total": 0, "results": []}`, NOT a 404:
         *     "no results for this filter" is a normal, valid response for a
         *     collection endpoint -- unlike a single-resource lookup such as
         *     GET /api/v1/players/{player_id}, where a missing id has no other
         *     reasonable interpretation, an empty collection is exactly what an
         *     empty collection should return.
         */
        get: operations["get_season_leaderboard_api_v1_leaderboards_season__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboards/all-time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Time Leaderboard
         * @description Ranks EVERY player-season in the table by `category`, regardless of
         *     season -- see this module's docstring for why that requires computing
         *     a fresh `RANK() OVER (ORDER BY <value column> DESC)` here rather than
         *     reusing the stored per-season rank column (which would repeat "rank 1"
         *     once per season instead of naming one true all-time best).
         *
         *     Only the value column itself needs a null check here (the stored
         *     per-season rank column is irrelevant to this endpoint and never
         *     referenced) -- `WHERE <value column> IS NOT NULL` runs before the
         *     window function, so RANK() is computed only over rows that actually
         *     have a value to rank, with no gap in the resulting 1..N sequence.
         */
        get: operations["get_all_time_leaderboard_api_v1_leaderboards_all_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryEnum
         * @description A `str, Enum` (rather than a plain string with regex/`Literal`
         *     validation) so FastAPI renders this as an actual dropdown of the 16
         *     valid values in Swagger UI, and so an invalid value gets FastAPI's
         *     native 422 enum-validation error for free, instead of a custom check
         *     in the route.
         * @enum {string}
         */
        CategoryEnum: "average_strokes_gained" | "average_strokes_gained_putting" | "average_strokes_gained_around_green" | "average_strokes_gained_approach" | "average_strokes_gained_off_tee" | "average_strokes_gained_tee_to_green" | "strokes_gained" | "strokes_gained_putting" | "strokes_gained_around_green" | "strokes_gained_approach" | "strokes_gained_off_tee" | "strokes_gained_tee_to_green" | "wins" | "top_5_finishes" | "top_10_finishes" | "cuts_made";
        /** CourseResponse */
        CourseResponse: {
            /** Courseid */
            courseId: number;
            /** Course */
            course: string;
            /** Tournamentshosted */
            tournamentsHosted: number;
            /** Averagestrokesvspar */
            averageStrokesVsPar: number;
            /** Averagestrokesvsparrank */
            averageStrokesVsParRank: number;
            /** Averagestrokesgained */
            averageStrokesGained: number | null;
            /** Averagestrokesgainedputting */
            averageStrokesGainedPutting: number | null;
            /** Averagestrokesgainedaroundgreen */
            averageStrokesGainedAroundGreen: number | null;
            /** Averagestrokesgainedapproach */
            averageStrokesGainedApproach: number | null;
            /** Averagestrokesgainedofftee */
            averageStrokesGainedOffTee: number | null;
            /** Difficultyrank */
            difficultyRank: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedResponse */
        PaginatedResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Results */
            results: unknown[];
        };
        /**
         * PlayerCareerSummary
         * @description Computed via aggregate SQL across all of a player's seasons (see
         *     api/routers/players.py's career query) -- not a raw DB row, so unlike
         *     CourseResponse/PlayerSeason there's no 1:1 column to alias from.
         */
        PlayerCareerSummary: {
            /** Playerid */
            playerId: number;
            /** Player */
            player: string;
            /** Seasonsplayed */
            seasonsPlayed: number;
            /** Tournamentsplayed */
            tournamentsPlayed: number;
            /** Wins */
            wins: number;
            /** Top5Finishes */
            top5Finishes: number;
            /** Top10Finishes */
            top10Finishes: number;
            /** Cutsmade */
            cutsMade: number;
            /** Careeraveragestrokesgained */
            careerAverageStrokesGained: number | null;
            /** Careerstrokesgained */
            careerStrokesGained: number | null;
            /** Firstseason */
            firstSeason: number;
            /** Lastseason */
            lastSeason: number;
        };
        /**
         * PlayerSeason
         * @description One row of `player_season_stats`, in full -- returned by
         *     GET /api/v1/players/{player_id}/seasons.
         */
        PlayerSeason: {
            /** Playerid */
            playerId: number;
            /** Season */
            season: number;
            /** Player */
            player: string;
            /** Tournamentsplayed */
            tournamentsPlayed: number;
            /** Wins */
            wins: number;
            /** Top5Finishes */
            top5Finishes: number;
            /** Top10Finishes */
            top10Finishes: number;
            /** Cutsmade */
            cutsMade: number;
            /** Averagestrokesgained */
            averageStrokesGained: number | null;
            /** Averagestrokesgainedputting */
            averageStrokesGainedPutting: number | null;
            /** Averagestrokesgainedaroundgreen */
            averageStrokesGainedAroundGreen: number | null;
            /** Averagestrokesgainedapproach */
            averageStrokesGainedApproach: number | null;
            /** Averagestrokesgainedofftee */
            averageStrokesGainedOffTee: number | null;
            /** Averagestrokesgainedteetogreen */
            averageStrokesGainedTeeToGreen: number | null;
            /** Strokesgained */
            strokesGained: number | null;
            /** Strokesgainedputting */
            strokesGainedPutting: number | null;
            /** Strokesgainedaroundgreen */
            strokesGainedAroundGreen: number | null;
            /** Strokesgainedapproach */
            strokesGainedApproach: number | null;
            /** Strokesgainedofftee */
            strokesGainedOffTee: number | null;
            /** Strokesgainedteetogreen */
            strokesGainedTeeToGreen: number | null;
            /** Averagestrokesgainedrank */
            averageStrokesGainedRank: number | null;
            /** Averagestrokesgainedputtingrank */
            averageStrokesGainedPuttingRank: number | null;
            /** Averagestrokesgainedaroundgreenrank */
            averageStrokesGainedAroundGreenRank: number | null;
            /** Averagestrokesgainedapproachrank */
            averageStrokesGainedApproachRank: number | null;
            /** Averagestrokesgainedoffteerank */
            averageStrokesGainedOffTeeRank: number | null;
            /** Averagestrokesgainedteetogreenrank */
            averageStrokesGainedTeeToGreenRank: number | null;
            /** Strokesgainedrank */
            strokesGainedRank: number;
            /** Strokesgainedputtingrank */
            strokesGainedPuttingRank: number;
            /** Strokesgainedaroundgreenrank */
            strokesGainedAroundGreenRank: number;
            /** Strokesgainedapproachrank */
            strokesGainedApproachRank: number;
            /** Strokesgainedoffteerank */
            strokesGainedOffTeeRank: number;
            /** Strokesgainedteetogreenrank */
            strokesGainedTeeToGreenRank: number;
            /** Averagestrokesgainedpreviousseason */
            averageStrokesGainedPreviousSeason: number | null;
            /** Averagestrokesgaineddelta */
            averageStrokesGainedDelta: number | null;
        };
        /**
         * PlayerSummary
         * @description List/search-mode shape -- just enough to identify a player and let
         *     a caller drill into GET /api/v1/players/{player_id}. There's no
         *     single "player" row to return more of: every DB row is one
         *     player-season, so anything beyond id/name is necessarily an aggregate
         *     (see PlayerCareerSummary) or per-season (see PlayerSeason), not a flat
         *     field on this model.
         */
        PlayerSummary: {
            /** Playerid */
            playerId: number;
            /** Player */
            player: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_courses_api_v1_courses__get: {
        parameters: {
            query?: {
                /** @description Max rows to return in browse mode. Ignored in search mode (fixed at 10 -- see `search`). */
                limit?: number;
                /** @description Rows to skip in browse mode. Ignored in search mode. */
                offset?: number;
                /** @description Case-insensitive partial match on course name. Switches the endpoint to search mode -- see below. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"] | components["schemas"]["CourseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_api_v1_players__get: {
        parameters: {
            query?: {
                /** @description Max rows to return in browse mode. Ignored in search mode (fixed at 10 -- see `search`). */
                limit?: number;
                /** @description Rows to skip in browse mode. Ignored in search mode. */
                offset?: number;
                /** @description Case-insensitive partial match on player name. Switches the endpoint to search mode -- see below. */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"] | components["schemas"]["PlayerSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_career_summary_api_v1_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCareerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_seasons_api_v1_players__player_id__seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSeason"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_season_leaderboard_api_v1_leaderboards_season__year__get: {
        parameters: {
            query: {
                /** @description Which stat to rank players by. */
                category: components["schemas"]["CategoryEnum"];
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_time_leaderboard_api_v1_leaderboards_all_time_get: {
        parameters: {
            query: {
                /** @description Which stat to rank players by. */
                category: components["schemas"]["CategoryEnum"];
                /** @description Max rows to return. */
                limit?: number;
                /** @description Rows to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
